---
abstract: 'Dancer2 logger engine for Sys::Syslog'
author:
  - 'Andy Beverley <andy@andybev.com>'
build_requires:
  Dancer2: 0.151
  File::Spec: 0
  File::Temp: 0
  HTTP::Request::Common: 0
  IO::Handle: 0
  IPC::Open3: 0
  Plack::Test: 0
  Test::More: 0.94
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Logger-Syslog
requires:
  Dancer2::Core::Role::Logger: 0
  Dancer2::Core::Types: 0
  File::Basename: 0
  Moo: 0
  Sys::Syslog: 0
version: 0.01
